[build]
  command = "yarn build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "15.5.1"
  YARN_VERSION = "1.22.10"

[[redirects]]
  from = "https://afara.netlify.com/*"
  to = "https://afara.foundation/:splat"
  force = true